site_name: Saros # Change this to your site name
site_description: Saros Wiki
site_url: https://spankadin.github.io/Saros-Wiki/ # Change this to your site URL
site_author: Spankadin

theme:
    name: 'material'
    logo: _assets/meta/dice.png
    favicon: _assets/meta/dice.png
    custom_dir: overrides
    font:
        text: Karla
        code: Ubuntu Mono
    language: En
    palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Light of The Two Suns

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Sarosian Moons Light
    features:
        - navigation.indexes
        - navigation.instant
        - navigation.instant.progress
        - navigation.instant.preview
        - navigation.top
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.content
        - navigation.path
        - navigation.tracking
        - search.suggest
        - search.highlight
        - search.share
        - toc.follow
# Extensions
markdown_extensions:
  - footnotes
  - nl2br
  - attr_list
  - md_in_html
  - sane_lists
  - meta
  - smarty
  - tables
  - mdx_breakless_lists
  - def_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.tasklist:
       custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/icons
  - admonition
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: dataview
          class: dataview
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: folderv
          class: folderv
          format: !!python/name:pymdownx.superfences.fence_div_format
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
      preserve_tabs: true
plugins:
  - search
  - meta-descriptions
  - awesome-pages
  - tags:
      tags_file: tags.md
  - blog:
      blog_dir: blog
      blog_toc: true
      post_readtime_words_per_minute: 300
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      locale: en
      custom_format: "%A %d %B %Y"
      enable_creation_date: true
  - ezlinks:
      wikilinks: true
      relative_links: true  # Forces relative links instead of stripping folders
  - embed_file:
      callouts: true
      custom-attributes: '_static/css/custom_attributes.css'
  - custom-attributes:
      file: '_static/css/custom_attributes.css'
  - callouts
  - glightbox
hooks:
  - overrides/hooks/on_page_markdown.py
  - overrides/hooks/on_env.py
  - overrides/hooks/on_post_page.py
extra_javascript:
  - _static/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - _static/js/snippets.js
  - https://cdn.jsdelivr.net/gh/Enveloppe/_static@refs/heads/master/dist/index.js

extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css
    - _static/css/admonition.css
    - _static/css/custom_attributes.css
    - _static/css/customization.css
    - https://cdn.jsdelivr.net/gh/Enveloppe/_static@refs/heads/master/dist/styles.css
extra:
  SEO: '_assets/meta/logo.png'
  comments: False
  attachments: '_assets/img/'
  no-auto-h1: False
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Enveloppe/
  blog_list:
    pagination: true
    pagination_message: true
    pagination_translation: 'posts in'
    no_page_found: 'No pages found!'
  hooks:
    strip_comments: true
    fix_heading: true
  icons:
    folder: "icons/" #from root _assets ; see overrides/partials/nav-item.html and overrides/partials/tabs-item.html
    default:
      file: "file.svg"
      folder: "folder-open.svg"
      index: "index.svg"  
copyright: Copyright &copy; 2025 James McB


# Custom Homepage Elements
home_cover_image: docs/_assets/Saros.webp # This path starts at your root mkdocs directory.
home_tagline: Sarosian Wiki
home_description: |
  A wiki for all things Saros.

# Gradient Color
home_gradient_hsla: hsla(0deg,47%,55%,1) # Default Green: hsla(160deg,47%,55%,1)

# Custom Homepage Button(s)
home_button1_name: NPC Table                  # Comment this parameter out to remove the button.
home_button1_url: https://spankadin.github.io/Saros-Wiki/Tables-%26%20Tools/Dataview/NPCs/                       # This path starts at your root mkdocs directory.
home_button1_theme: md-button md-button--primary # Options: "md-button", "md-button md-button--primary"
#home_button1_icon: people                        # Options: "people", "gear", "image"
#home_button1_blurb: |                            # Short description of this button / section.
#  A table of all NPCs in Saros.

home_button2_name: House Rules   # Comment this parameter out to remove the button.
home_button2_url: https://spankadin.github.io/Saros-Wiki/Tables-%26%20Tools/R1.-House-Rules/    # This path starts at your root mkdocs directory.
home_button2_theme: md-button # Options: "md-button", "md-button md-button--primary"
#home_button2_icon: gear       # Options: "people", "gear", "image"
#home_button2_blurb: |         # Short description of this button / section.
#  Sarosian House Rules.

home_button3_name: Table Rules   # Comment this parameter out to remove the button.
home_button3_url: https://spankadin.github.io/Saros-Wiki/Tables-%26%20Tools/R2.-Table-Etiquette/    # This path starts at your root mkdocs directory.
home_button3_theme: md-button # Options: "md-button", "md-button md-button--primary"
#home_button3_icon: image      # Options: "people", "gear", "image"
#home_button3_blurb: |         # Short description of this button / section.
#  Rules for Sarosian Table Etiquette.

# Homepage Code Execution
home_execute_js: | # Javascript to execute when accessing the homepage
  console.log("This is an example!");
